<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Bug Bounty Report — Bug Bounty Report</title>
  <style>
    * { box-sizing: border-box; }
    body { font-family: 'Courier New', monospace; background: #0d1117; color: #c9d1d9;
            margin: 0; padding: 2em; line-height: 1.6; }
    h1 { color: #00d4ff; border-bottom: 2px solid #00d4ff; padding-bottom: .4em; }
    h2 { color: #58a6ff; margin-top: 2em; border-left: 4px solid #58a6ff; padding-left: .6em; }
    h3 { color: #8b949e; }
    .meta { background: #161b22; border: 1px solid #30363d; border-radius: 6px;
             padding: 1em; margin: 1em 0; }
    .meta td { padding: .3em 1em .3em 0; }
    .meta td:first-child { color: #8b949e; white-space: nowrap; }
    .severity { font-weight: bold; color: #00d4ff; background: #00d4ff22;
                 border: 1px solid #00d4ff; border-radius: 4px; padding: .1em .5em; }
    .code { background: #161b22; border: 1px solid #30363d; border-radius: 4px;
             padding: 1em; overflow-x: auto; white-space: pre-wrap; font-size: .85em;
             max-height: 400px; overflow-y: auto; }
    .highlight { background: #ff000033; border-left: 3px solid #ff4444; }
    .tag { display: inline-block; background: #21262d; border: 1px solid #30363d;
            border-radius: 4px; padding: .1em .5em; margin: .2em; font-size: .85em; }
    .footer { margin-top: 3em; border-top: 1px solid #21262d; padding-top: 1em;
               color: #484f58; font-size: .8em; }
    a { color: #58a6ff; }
  </style>
</head>
<body>
<h1>Bug Bounty Report</h1>
<p>Template: Generic · Findings: 10 · Generated: 2026-04-30 18:55:27 UTC</p>
<h2 style="color:#ffcc00">MEDIUM (10)</h2>
<h3>Reflected XSS (HEADER)</h3>
<p><strong>URL:</strong> https://xss-game.appspot.com</p>
<p><strong>Parameter:</strong> Referer</p>
<div class="code">[header:Referer] Payload reflected unescaped</div>
<h3>Reflected XSS (HEADER)</h3>
<p><strong>URL:</strong> https://xss-game.appspot.com</p>
<p><strong>Parameter:</strong> User-Agent</p>
<div class="code">[header:User-Agent] Payload reflected unescaped</div>
<h3>Reflected XSS (HEADER)</h3>
<p><strong>URL:</strong> https://xss-game.appspot.com</p>
<p><strong>Parameter:</strong> X-Forwarded-For</p>
<div class="code">[header:X-Forwarded-For] Payload reflected unescaped</div>
<h3>Reflected XSS (HEADER)</h3>
<p><strong>URL:</strong> https://xss-game.appspot.com</p>
<p><strong>Parameter:</strong> X-Real-IP</p>
<div class="code">[header:X-Real-IP] Payload reflected unescaped</div>
<h3>Reflected XSS (HEADER)</h3>
<p><strong>URL:</strong> https://xss-game.appspot.com</p>
<p><strong>Parameter:</strong> X-Forwarded-Host</p>
<div class="code">[header:X-Forwarded-Host] Payload reflected unescaped</div>
<h3>Reflected XSS (HEADER)</h3>
<p><strong>URL:</strong> https://xss-game.appspot.com</p>
<p><strong>Parameter:</strong> X-Original-URL</p>
<div class="code">[header:X-Original-URL] Payload reflected unescaped</div>
<h3>Reflected XSS (HEADER)</h3>
<p><strong>URL:</strong> https://xss-game.appspot.com</p>
<p><strong>Parameter:</strong> X-Custom-IP-Authorization</p>
<div class="code">[header:X-Custom-IP-Authorization] Payload reflected unescaped</div>
<h3>Reflected XSS (HEADER)</h3>
<p><strong>URL:</strong> https://xss-game.appspot.com</p>
<p><strong>Parameter:</strong> X-Rewrite-URL</p>
<div class="code">[header:X-Rewrite-URL] Payload reflected unescaped</div>
<h3>Reflected XSS (HEADER)</h3>
<p><strong>URL:</strong> https://xss-game.appspot.com</p>
<p><strong>Parameter:</strong> X-Host</p>
<div class="code">[header:X-Host] Payload reflected unescaped</div>
<h3>Reflected XSS (HEADER)</h3>
<p><strong>URL:</strong> https://xss-game.appspot.com</p>
<p><strong>Parameter:</strong> X-HTTP-Host-Override</p>
<div class="code">[header:X-HTTP-Host-Override] Payload reflected unescaped</div>
<div class="footer">
  Generated by <strong>Pentool PRO Reports</strong> · 2026-04-30 18:55:27 UTC
</div>
</body>
</html>
