"""FREE HTML exporter — minimal, self-contained, one page.

The template is inlined (zero external dependencies) so the .html file
can be opened in any browser, emailed, or attached to a ticket.
"""

from __future__ import annotations

import html as _html

from pentool.export import (
    BaseExporter,
    FindingData,
    ReportData,
    SEVERITY_COLOR,
    SEVERITY_EMOJI,
)


class HtmlExporter(BaseExporter):
    """FREE: minimal HTML report — one page, inline CSS, no deps."""

    def extension(self) -> str:
        return "html"

    def export(self, report: ReportData) -> str:
        head = self._build_head(report)
        body = self._build_body(report)
        return f"""<!DOCTYPE html>
<html lang="en">
<head>
{head}
</head>
<body>
{body}
</body>
</html>"""

    # ── private helpers ─────────────────────────────────────────────────

    CSS = """
* { margin: 0; padding: 0; box-sizing: border-box; }
body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
       background: #f8f9fa; color: #212529; padding: 2rem 1rem; }
.container { max-width: 960px; margin: 0 auto; background: #fff;
             border-radius: 8px; box-shadow: 0 1px 3px rgba(0,0,0,.1); padding: 2rem; }
h1 { font-size: 1.6rem; margin-bottom: .25rem; }
.meta { color: #6c757d; font-size: .9rem; margin-bottom: 1.5rem; }
h2 { font-size: 1.2rem; margin: 1.5rem 0 .75rem; border-bottom: 2px solid #dee2e6; padding-bottom: .25rem; }
.summary { display: flex; gap: .5rem; flex-wrap: wrap; margin-bottom: 1.5rem; }
.badge { padding: .35rem .75rem; border-radius: 4px; font-size: .85rem; font-weight: 600; color: #fff; }
.badge-critical { background: #dc3545; }
.badge-high     { background: #fd7e14; }
.badge-medium   { background: #ffc107; color: #212529; }
.badge-low      { background: #0d6efd; }
.badge-info     { background: #6c757d; }
.finding { border: 1px solid #dee2e6; border-radius: 6px; padding: 1rem; margin-bottom: 1rem; }
.finding h3 { font-size: 1rem; margin-bottom: .5rem; }
.finding .field { font-size: .85rem; color: #495057; margin: .25rem 0; }
.finding .field strong { color: #212529; }
pre { background: #f1f3f5; padding: .75rem; border-radius: 4px; font-size: .8rem;
      overflow-x: auto; margin: .5rem 0; white-space: pre-wrap; word-break: break-word; }
.footer { text-align: center; color: #adb5bd; font-size: .8rem; margin-top: 2rem; }
"""

    def _build_head(self, report: ReportData) -> str:
        return f"""<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Pentool Report — {_html.escape(report.target)}</title>
<style>
{self.CSS}
</style>"""

    def _build_body(self, report: ReportData) -> str:
        lines = ['<div class="container">']
        self._write_header(lines, report)
        self._write_summary(lines, report)
        self._write_findings(lines, report)
        lines.append('<div class="footer">Generated by Pentool</div>')
        lines.append("</div>")
        return "\n".join(lines)

    def _write_header(self, lines: list[str], report: ReportData) -> None:
        lines.append(f"<h1>Pentool Scan Report</h1>")
        meta = f"<strong>Target:</strong> {_html.escape(report.target)}"
        if report.end_time or report.start_time:
            meta += f" &middot; {_html.escape(report.end_time or report.start_time)}"
        if report.tool_version:
            meta += f" &middot; pentool {_html.escape(report.tool_version)}"
        lines.append(f'<div class="meta">{meta}</div>')

    def _write_summary(self, lines: list[str], report: ReportData) -> None:
        total = sum(report.summary.values())
        lines.append("<h2>Summary</h2>")
        lines.append(f"<p><strong>Total findings:</strong> {total}</p>")
        lines.append('<div class="summary">')
        for sev in ("critical", "high", "medium", "low", "info"):
            cnt = report.summary.get(sev, 0)
            if cnt:
                lines.append(f'<span class="badge badge-{sev}">{_html.escape(sev.capitalize())}: {cnt}</span>')
        lines.append("</div>")

    def _write_findings(self, lines: list[str], report: ReportData) -> None:
        if not report.findings:
            lines.append("<h2>Findings</h2><p><em>No findings to report.</em></p>")
            return
        lines.append("<h2>Findings</h2>")
        for f in report.findings:
            color = SEVERITY_COLOR.get(f.severity.lower(), "#6c757d")
            lines.append(f'<div class="finding" style="border-left: 4px solid {color};">')
            emoji = SEVERITY_EMOJI.get(f.severity, "")
            lines.append(f"<h3>{emoji} [{f.severity.upper()}] {_html.escape(f.title)}</h3>")
            if f.url:
                lines.append(f'<div class="field"><strong>URL:</strong> {_html.escape(f.url)}</div>')
            if f.parameter:
                lines.append(f'<div class="field"><strong>Parameter:</strong> {_html.escape(f.parameter)}</div>')
            if f.payload:
                lines.append(f'<div class="field"><strong>Payload:</strong> <code>{_html.escape(f.payload)}</code></div>')
            if f.cwe:
                lines.append(f'<div class="field"><strong>CWE:</strong> {f.cwe}</div>')
            if f.cvss:
                lines.append(f'<div class="field"><strong>CVSS:</strong> {f.cvss}</div>')
            lines.append(f'<div class="field"><strong>Confidence:</strong> {f.confidence}</div>')
            if f.description:
                lines.append(f"<p>{_html.escape(f.description)}</p>")
            if f.evidence:
                lines.append("<strong>Evidence:</strong><pre>")
                lines.append(_html.escape(f.evidence[:500]))
                lines.append("</pre>")
            if f.remediation:
                lines.append(f'<div class="field"><strong>Remediation:</strong> {_html.escape(f.remediation)}</div>')
            lines.append("</div>")