"""FREE Markdown exporter — short, self-contained report."""

from __future__ import annotations

from pentool.export import (
    BaseExporter,
    FindingData,
    ReportData,
    SEVERITY_EMOJI,
)


class MarkdownExporter(BaseExporter):
    """FREE: minimal Markdown report.

    Produces a plain .md file that renders well on GitHub / GitLab / any
    Markdown viewer.  No external dependencies.
    """

    def extension(self) -> str:
        return "md"

    def export(self, report: ReportData) -> str:
        lines: list[str] = []
        self._write_header(lines, report)
        self._write_summary(lines, report)
        self._write_findings(lines, report)
        self._write_footer(lines)
        return "\n".join(lines)

    # ── private helpers ─────────────────────────────────────────────────

    def _write_header(self, lines: list[str], report: ReportData) -> None:
        lines.append(f"# Pentool Scan Report")
        lines.append("")
        lines.append(f"**Target:** {report.target}")
        lines.append(f"**Date:** {report.end_time or report.start_time or 'N/A'}")
        if report.tool_version:
            lines.append(f"**Tool:** pentool {report.tool_version}")
        lines.append("")

    def _write_summary(self, lines: list[str], report: ReportData) -> None:
        total = sum(report.summary.values())
        lines.append("## Summary")
        lines.append("")
        lines.append(f"**Total findings:** {total}")
        for sev in ("critical", "high", "medium", "low", "info"):
            cnt = report.summary.get(sev, 0)
            emoji = SEVERITY_EMOJI.get(sev, "")
            lines.append(f"- {emoji} **{sev.capitalize()}:** {cnt}")
        lines.append("")

    def _write_findings(self, lines: list[str], report: ReportData) -> None:
        if not report.findings:
            lines.append("## Findings")
            lines.append("")
            lines.append("_No findings to report._")
            lines.append("")
            return

        for i, f in enumerate(report.findings, 1):
            emoji = SEVERITY_EMOJI.get(f.severity, "")
            lines.append(f"### {emoji} [{f.severity.upper()}] {f.title}")
            lines.append("")
            if f.url:
                lines.append(f"**URL:** `{f.url}`")
            if f.parameter:
                lines.append(f"**Parameter:** `{f.parameter}`")
            if f.payload:
                lines.append(f"**Payload:** `{f.payload}`")
            if f.cwe:
                lines.append(f"**CWE:** {f.cwe}")
            if f.cvss:
                lines.append(f"**CVSS:** {f.cvss}")
            lines.append(f"**Confidence:** {f.confidence}")
            lines.append("")
            if f.description:
                lines.append(f"{f.description}")
                lines.append("")
            if f.evidence:
                lines.append("**Evidence:**")
                lines.append("```")
                lines.append(f.evidence[:500])
                lines.append("```")
                lines.append("")
            if f.remediation:
                lines.append(f"**Remediation:** {f.remediation}")
                lines.append("")

    def _write_footer(self, lines: list[str]) -> None:
        lines.append("---")
        lines.append("")
        lines.append("_Generated by Pentool_")
        lines.append("")